import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "styles/pages/me/schedule/week/NotFound.module.scss";
import {
  getClosestStartDate,
  getCurrentStartDate,
} from "utils/helpers/dateTime";

const NotFound: NextPage = () => {
  const router = useRouter();
  const { startDate } = router.query;

  let alternativeStartDate;

  if (
    !startDate ||
    typeof startDate !== "string" ||
    getClosestStartDate(startDate) === "NaN/NaN/NaN"
  ) {
    alternativeStartDate = getCurrentStartDate();
  } else {
    alternativeStartDate = getClosestStartDate(startDate);
  }
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {startDate && typeof startDate === "string"
          ? `Week of ${startDate.replaceAll("/undefined", "")}`
          : "Page"}{" "}
        not found, did you mean to look for&nbsp;
        <Link href={`/me/schedule/week/${alternativeStartDate}`}>
          {`week of ${alternativeStartDate}`}
        </Link>
        ?
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req }) => ({
  props: {},
});

export default NotFound;
