import { Text, useToast, VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "styles/pages/me/schedule/week/NotFound.module.scss";
import {
  getClosestStartDate,
  getCurrentStartDate,
} from "utils/helpers/dateTime";

const WeekNotFound: NextPage = () => {
  const router = useRouter();
  const toast = useToast();
  const { startDate } = router.query;

  let alternativeStartDate;

  if (
    !startDate ||
    typeof startDate !== "string" ||
    getClosestStartDate(startDate) === "NaN/NaN/NaN"
  ) {
    alternativeStartDate = getCurrentStartDate();
  } else {
    alternativeStartDate = getClosestStartDate(startDate);
  }

  return (
    <div>
      <Head>
        <title>404: Page not found</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text
          as="h1"
          variant="h1"
          fontSize="1.5rem"
          padding="10px 23px 10px 0px"
          fontWeight="500"
          borderRight="1px solid rgba(0, 0, 0, 0.3)"
          color="black"
          marginRight="20px"
        >
          404
        </Text>{" "}
        <VStack>
          <Text>
            {startDate && typeof startDate === "string"
              ? `Week of ${startDate.replaceAll("/undefined", "")}`
              : "Page"}{" "}
            not found, did you mean to look for&nbsp;
            <Text
              as="a"
              onClick={() => {
                toast({
                  title: `Redirecting...`,
                  position: "top",
                  isClosable: true,
                  duration: 3000,
                  status: "info",
                });
              }}
              href={`/me/schedule/week/${alternativeStartDate}`}
            >
              {`week of ${alternativeStartDate}`}
            </Text>
            ?
          </Text>
        </VStack>
      </main>
    </div>
  );
};

export default WeekNotFound;
