import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

const Profile: NextPage = () => (
  <div>
    <Head>
      <title>Profile</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>Profile Page Placeholder</main>
  </div>
);

export const getServerSideProps: GetServerSideProps = async ({ req }) => ({
  props: {},
});

export default Profile;
