import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import { getSession, signOut, useSession } from "next-auth/react";
import connectToDatabase from "utils/database/mongodb";

const Me: NextPage = () => {
  const { data: session, status } = useSession();

  const isLoading = status === "loading";

  return (
    <div>
      <Head>
        <title>Studee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome {session?.user?.email || "back!"}</h1>
        <button
          type="submit"
          disabled={isLoading}
          onClick={() => {
            signOut({ callbackUrl: `${window.location.origin}` })
              .then((res) => {})
              .catch((err) => {});
          }}
        >
          Sign Out
        </button>
      </main>

      <footer>Made with ❤️ by Anthony Hien Vu</footer>
    </div>
  );
};

export default Me;

export const getServerSideProps = async (context: NextPageContext) => {
  try {
    await connectToDatabase();
    const session = await getSession(context);

    // Redirect to home/login page if not logged in.
    if (!session) {
      return {
        redirect: {
          destination: "/",
          permanent: false,
        },
      };
    }

    // Fetch current week's study schedule data here and return props to component.
    return {
      props: { session },
    };
  } catch (e) {
    // eslint-disable-next-line no-console
    console.error(e);
    return {
      props: {},
    };
  }
};
