import type { NextPage } from "next";
import Head from "next/head";
import styles from "styles/pages/me.module.scss";

const Me: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Studee</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1>Welcome</h1>
      <h2>Welcome</h2>
      <h3>Welcome</h3>
    </main>
  </div>
);

export default Me;

export const getServerSideProps = async () => {
  try {
    return {
      props: {},
    };
  } catch (e) {
    // eslint-disable-next-line no-console
    console.error(e);
    return {
      props: {},
    };
  }
};
